model:
  tensor_shape: !!python/tuple [200, 100, 200]
  h_dim: !!python/tuple [256, 256] #[512, 512]
  act: 'relu'
  latent_dim: 64
  noise_sigma: 0.2 #0.2
  sigma_level: 10 #10
  x_emb_size: 1
  sigma_func: 'softplus'
  dropout: 0.0
  pooling_method: 'cat'
  skip_connection: true

train:
  epoch: 1000 #1000
  lr: 0.001 #0.001
  weight_decay: 0.0
  batch_size: 256
  mile_stones: !!python/tuple [0.2, 0.5, 0.8]
  scheduler: 'cosine'
  eval_int: 1
  grad_clip: 5.0
  grad_clip_norm: 'inf'
  log_grad_norm: false
